import { Rate } from '@eltizamati/domain'
import type { FinancialInstitution, FinancingProduct, SourceRecord } from './catalogue'

export const CATALOGUE_SNAPSHOT_VERIFIED_AT = '2026-07-15'
export const SOURCE_RECORDS: readonly SourceRecord[] = [
  { id: 'cbj-banking-guide', publisherName: 'Central Bank of Jordan', publisherType: 'regulator', title: 'Banking Sector Guide', sourceUrl: 'https://www.cbj.gov.jo/EN/Pages/Bankingsectorguide', language: 'en', retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT, publishedAt: null, effectiveFrom: null, effectiveUntil: null, contentHash: null, reviewStatus: 'verified', reviewedBy: 'manual-review', notes: 'Institution inventory reference.' },
  { id: 'jib-housing', publisherName: 'Jordan Islamic Bank', publisherType: 'bank', title: 'Housing finance campaign', sourceUrl: 'https://www.jordanislamicbank.com/en/housing-finance', language: 'en', retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT, publishedAt: null, effectiveFrom: null, effectiveUntil: null, contentHash: null, reviewStatus: 'verified', reviewedBy: 'manual-review', notes: 'Campaign terms must be confirmed directly with the bank.' },
  { id: 'jib-murabaha', publisherName: 'Jordan Islamic Bank', publisherType: 'bank', title: 'Murabaha', sourceUrl: 'https://www.jordanislamicbank.com/ar/loan/murabaha', language: 'ar', retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT, publishedAt: null, effectiveFrom: null, effectiveUntil: null, contentHash: null, reviewStatus: 'verified', reviewedBy: 'manual-review', notes: 'Published calculator labels results as approximate.' },
]

export const FINANCIAL_INSTITUTIONS: readonly FinancialInstitution[] = [
  { id: 'arab-bank', nameEn: 'Arab Bank PLC', nameAr: 'البنك العربي', institutionType: 'jordanian-bank', bankingModel: 'conventional', website: 'https://www.arabbank.com.jo', sourceId: 'cbj-banking-guide', status: 'partially-verified', lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT },
  { id: 'bank-of-jordan', nameEn: 'Bank of Jordan PLC', nameAr: 'بنك الأردن', institutionType: 'jordanian-bank', bankingModel: 'conventional', website: 'https://bankofjordan.com/en', sourceId: 'cbj-banking-guide', status: 'no-public-product-data-found', lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT },
  { id: 'cairo-amman', nameEn: 'Cairo Amman Bank', nameAr: 'بنك القاهرة عمان', institutionType: 'jordanian-bank', bankingModel: 'conventional', website: 'https://www.cab.jo', sourceId: 'cbj-banking-guide', status: 'pending-review', lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT },
  { id: 'jordan-islamic', nameEn: 'Jordan Islamic Bank', nameAr: 'البنك الإسلامي الأردني', institutionType: 'jordanian-bank', bankingModel: 'islamic', website: 'https://www.jordanislamicbank.com/en', sourceId: 'cbj-banking-guide', status: 'verified', lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT },
  { id: 'housing-bank', nameEn: 'Housing Bank for Trade and Finance', nameAr: 'بنك الإسكان للتجارة والتمويل', institutionType: 'jordanian-bank', bankingModel: 'conventional', website: 'https://www.hbtf.com', sourceId: 'cbj-banking-guide', status: 'pending-review', lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT },
]

export const FINANCING_PRODUCTS: readonly FinancingProduct[] = [
  { id: 'jib-housing-murabaha', institutionId: 'jordan-islamic', nameEn: 'Housing and furniture Murabaha campaign', nameAr: 'تمويل السكن والأثاث بالمرابحة', category: 'housing', structure: 'murabaha', amountRange: { minimum: null, maximum: null }, termMonths: { minimum: null, maximum: 84 }, pricing: { kind: 'profit-rate', minimumAnnualRate: Rate.fromPercent('1'), maximumAnnualRate: null, benchmarkName: null, margin: null, effectiveRatePublished: null }, salaryTransfer: 'not-published', earlySettlementText: null, sourceIds: ['jib-housing'], lastVerifiedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT, completeness: 'partial', status: 'active' },
  { id: 'jib-general-murabaha', institutionId: 'jordan-islamic', nameEn: 'Murabaha for purchase', nameAr: 'مرابحة للآمر بالشراء', category: 'other', structure: 'murabaha', amountRange: { minimum: null, maximum: null }, termMonths: { minimum: null, maximum: null }, pricing: { kind: 'profit-rate', minimumAnnualRate: null, maximumAnnualRate: null, benchmarkName: null, margin: null, effectiveRatePublished: null }, salaryTransfer: 'not-published', earlySettlementText: null, sourceIds: ['jib-murabaha'], lastVerifiedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT, completeness: 'minimal', status: 'active' },
  { id: 'snapshot-conventional-unverified', institutionId: 'arab-bank', nameEn: 'Consumer financing — published details pending review', nameAr: 'تمويل للأفراد — تفاصيل منشورة قيد المراجعة', category: 'personal', structure: 'conventional-loan', amountRange: { minimum: null, maximum: null }, termMonths: { minimum: null, maximum: null }, pricing: { kind: 'not-published', minimumAnnualRate: null, maximumAnnualRate: null, benchmarkName: null, margin: null, effectiveRatePublished: null }, salaryTransfer: 'not-published', earlySettlementText: null, sourceIds: ['cbj-banking-guide'], lastVerifiedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT, completeness: 'minimal', status: 'pending-review' },
]
