import { Money, Rate } from '@eltizamati/domain'
import type { FinancialInstitution, FinancingProduct, SourceRecord } from './catalogue'

export const CATALOGUE_SNAPSHOT_VERIFIED_AT = '2026-07-15'
export const SOURCE_RECORDS: readonly SourceRecord[] = [
  {
    id: 'cbj-banking-guide',
    publisherName: 'Central Bank of Jordan',
    publisherType: 'regulator',
    title: 'Banking Sector Guide',
    sourceUrl: 'https://www.cbj.gov.jo/EN/Pages/Bankingsectorguide',
    language: 'en',
    retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes: 'Institution inventory reference.',
  },
  {
    id: 'jib-housing',
    publisherName: 'Jordan Islamic Bank',
    publisherType: 'bank',
    title: 'Housing finance campaign',
    sourceUrl: 'https://www.jordanislamicbank.com/en/housing-finance',
    language: 'en',
    retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes: 'Campaign terms must be confirmed directly with the bank.',
  },
  {
    id: 'jib-murabaha',
    publisherName: 'Jordan Islamic Bank',
    publisherType: 'bank',
    title: 'Murabaha',
    sourceUrl: 'https://www.jordanislamicbank.com/ar/loan/murabaha',
    language: 'ar',
    retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes: 'Published calculator labels results as approximate.',
  },
  {
    id: 'hbtf-automated-personal',
    publisherName: 'Housing Bank',
    publisherType: 'bank',
    title: 'Automated Personal Loan',
    sourceUrl: 'https://hbtf.com/en/automated-personal-loan',
    language: 'en',
    retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes: 'Published page requires transferred salary and states a JOD 20,000 maximum.',
  },
  {
    id: 'hbtf-rates-2026',
    publisherName: 'Housing Bank',
    publisherType: 'bank',
    title: 'Interest Rates and Fees Retail and Corporate Loans 2026',
    sourceUrl:
      'https://hbtf.com/uploads/2026/01/interest-rates-and-fees-retail-and-corporate-loans-2026.pdf',
    language: 'en',
    retrievedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    publishedAt: '2026-01-01',
    effectiveFrom: '2026-01-12',
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes:
      'Published rate is benchmark-linked and adjusted every three months; final pricing depends on published conditions.',
  },
  {
    id: 'jib-car-financing',
    publisherName: 'Jordan Islamic Bank',
    publisherType: 'bank',
    title: 'Islamic Car Financing — New & Used Vehicle Murabaha',
    sourceUrl: 'https://www.jordanislamicbank.com/en/my-car-financing',
    language: 'en',
    retrievedAt: '2026-07-18',
    publishedAt: null,
    effectiveFrom: '2026-06-21',
    effectiveUntil: '2026-08-31',
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes:
      'Published rate is a time-limited campaign (2026-06-21 to 2026-08-31) — re-verify after that window closes.',
  },
  {
    id: 'hbtf-auto-loan',
    publisherName: 'Housing Bank',
    publisherType: 'bank',
    title: 'Auto Loan',
    sourceUrl: 'https://hbtf.com/en/retail/loans/auto-loan',
    language: 'en',
    retrievedAt: '2026-07-18',
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes: 'Page states the rate depends on income, income source, and customer classification.',
  },
  {
    id: 'boj-auto-loan',
    publisherName: 'Bank of Jordan',
    publisherType: 'bank',
    title: '50/50 Auto Loan',
    sourceUrl: 'https://bankofjordan.com/en/loans/auto-loans',
    language: 'en',
    retrievedAt: '2026-07-18',
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes: 'Structure-only campaign page; no interest rate figure published.',
  },
  {
    id: 'safwa-car-financing',
    publisherName: 'Safwa Islamic Bank',
    publisherType: 'bank',
    title: 'Cars Financing',
    sourceUrl: 'https://www.safwabank.com/en/product/cars/',
    language: 'en',
    retrievedAt: '2026-07-18',
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes:
      'Page states the profit rate is fixed for the financing period but does not disclose the percentage.',
  },
  {
    id: 'ahli-finance-and-go',
    publisherName: 'Jordan Ahli Bank',
    publisherType: 'bank',
    title: 'Finance & Go — Auto Loan',
    sourceUrl: 'https://ahli.com/personal/auto-loans/finance-and-go/',
    language: 'en',
    retrievedAt: '2026-07-18',
    publishedAt: null,
    effectiveFrom: null,
    effectiveUntil: null,
    contentHash: null,
    reviewStatus: 'verified',
    reviewedBy: 'manual-review',
    notes: 'Rate published as a flat-rate "starting from" figure — actual rate may be higher.',
  },
]

export const FINANCIAL_INSTITUTIONS: readonly FinancialInstitution[] = [
  {
    id: 'arab-bank',
    nameEn: 'Arab Bank PLC',
    nameAr: 'البنك العربي',
    institutionType: 'jordanian-bank',
    bankingModel: 'conventional',
    website: 'https://www.arabbank.com.jo',
    sourceId: 'cbj-banking-guide',
    status: 'partially-verified',
    lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
  },
  {
    id: 'bank-of-jordan',
    nameEn: 'Bank of Jordan PLC',
    nameAr: 'بنك الأردن',
    institutionType: 'jordanian-bank',
    bankingModel: 'conventional',
    website: 'https://bankofjordan.com/en',
    sourceId: 'cbj-banking-guide',
    status: 'partially-verified',
    lastReviewedAt: '2026-07-18',
  },
  {
    id: 'cairo-amman',
    nameEn: 'Cairo Amman Bank',
    nameAr: 'بنك القاهرة عمان',
    institutionType: 'jordanian-bank',
    bankingModel: 'conventional',
    website: 'https://www.cab.jo',
    sourceId: 'cbj-banking-guide',
    status: 'pending-review',
    lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
  },
  {
    id: 'jordan-islamic',
    nameEn: 'Jordan Islamic Bank',
    nameAr: 'البنك الإسلامي الأردني',
    institutionType: 'jordanian-bank',
    bankingModel: 'islamic',
    website: 'https://www.jordanislamicbank.com/en',
    sourceId: 'cbj-banking-guide',
    status: 'verified',
    lastReviewedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
  },
  {
    id: 'housing-bank',
    nameEn: 'Housing Bank for Trade and Finance',
    nameAr: 'بنك الإسكان للتجارة والتمويل',
    institutionType: 'jordanian-bank',
    bankingModel: 'conventional',
    website: 'https://www.hbtf.com',
    sourceId: 'cbj-banking-guide',
    status: 'partially-verified',
    lastReviewedAt: '2026-07-18',
  },
  {
    id: 'safwa-islamic',
    nameEn: 'Safwa Islamic Bank',
    nameAr: 'بنك صفوة الإسلامي',
    institutionType: 'jordanian-bank',
    bankingModel: 'islamic',
    website: 'https://www.safwabank.com',
    sourceId: 'cbj-banking-guide',
    status: 'partially-verified',
    lastReviewedAt: '2026-07-18',
  },
  {
    id: 'jordan-ahli',
    nameEn: 'Jordan Ahli Bank',
    nameAr: 'البنك الأهلي الأردني',
    institutionType: 'jordanian-bank',
    bankingModel: 'conventional',
    website: 'https://ahli.com',
    sourceId: 'cbj-banking-guide',
    status: 'partially-verified',
    lastReviewedAt: '2026-07-18',
  },
]

export const FINANCING_PRODUCTS: readonly FinancingProduct[] = [
  {
    id: 'jib-housing-murabaha',
    institutionId: 'jordan-islamic',
    nameEn: 'Housing and furniture Murabaha campaign',
    nameAr: 'تمويل السكن والأثاث بالمرابحة',
    category: 'housing',
    structure: 'murabaha',
    amountRange: { minimum: null, maximum: null },
    termMonths: { minimum: null, maximum: 84 },
    pricing: {
      kind: 'profit-rate',
      minimumAnnualRate: Rate.fromPercent('1'),
      maximumAnnualRate: null,
      benchmarkName: null,
      margin: null,
      effectiveRatePublished: null,
    },
    salaryTransfer: 'not-published',
    earlySettlementText: null,
    sourceIds: ['jib-housing'],
    lastVerifiedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    completeness: 'partial',
    status: 'active',
  },
  {
    id: 'jib-general-murabaha',
    institutionId: 'jordan-islamic',
    nameEn: 'Murabaha for purchase',
    nameAr: 'مرابحة للآمر بالشراء',
    category: 'other',
    structure: 'murabaha',
    amountRange: { minimum: null, maximum: null },
    termMonths: { minimum: null, maximum: null },
    pricing: {
      kind: 'profit-rate',
      minimumAnnualRate: null,
      maximumAnnualRate: null,
      benchmarkName: null,
      margin: null,
      effectiveRatePublished: null,
    },
    salaryTransfer: 'not-published',
    earlySettlementText: null,
    sourceIds: ['jib-murabaha'],
    lastVerifiedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    completeness: 'minimal',
    status: 'active',
  },
  {
    id: 'hbtf-automated-personal',
    institutionId: 'housing-bank',
    nameEn: 'Automated Personal Loan',
    nameAr: null,
    category: 'personal',
    structure: 'conventional-loan',
    amountRange: { minimum: null, maximum: Money.of('20000') },
    termMonths: { minimum: null, maximum: null },
    pricing: {
      kind: 'variable-interest',
      minimumAnnualRate: null,
      maximumAnnualRate: null,
      benchmarkName: 'Overnight Interbank',
      margin: 'Published pricing varies by customer segment; direct confirmation required.',
      effectiveRatePublished: null,
    },
    salaryTransfer: 'required',
    earlySettlementText: null,
    sourceIds: ['hbtf-automated-personal', 'hbtf-rates-2026'],
    lastVerifiedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    completeness: 'partial',
    status: 'active',
  },
  {
    id: 'snapshot-conventional-unverified',
    institutionId: 'arab-bank',
    nameEn: 'Consumer financing — published details pending review',
    nameAr: 'تمويل للأفراد — تفاصيل منشورة قيد المراجعة',
    category: 'personal',
    structure: 'conventional-loan',
    amountRange: { minimum: null, maximum: null },
    termMonths: { minimum: null, maximum: null },
    pricing: {
      kind: 'not-published',
      minimumAnnualRate: null,
      maximumAnnualRate: null,
      benchmarkName: null,
      margin: null,
      effectiveRatePublished: null,
    },
    salaryTransfer: 'not-published',
    earlySettlementText: null,
    sourceIds: ['cbj-banking-guide'],
    lastVerifiedAt: CATALOGUE_SNAPSHOT_VERIFIED_AT,
    completeness: 'minimal',
    status: 'pending-review',
  },
  {
    id: 'jib-car-murabaha',
    institutionId: 'jordan-islamic',
    nameEn: 'Islamic Car Financing — new & used vehicle Murabaha',
    nameAr: 'تمويل السيارات الإسلامي بالمرابحة',
    category: 'vehicle',
    structure: 'murabaha',
    amountRange: { minimum: null, maximum: null },
    termMonths: { minimum: null, maximum: 84 },
    pricing: {
      kind: 'profit-rate',
      minimumAnnualRate: Rate.fromPercent('3.33'),
      maximumAnnualRate: Rate.fromPercent('3.99'),
      benchmarkName: null,
      margin: null,
      effectiveRatePublished: null,
    },
    salaryTransfer: 'optional',
    earlySettlementText: 'Bank states it accepts early settlement; specific terms not detailed.',
    sourceIds: ['jib-car-financing'],
    lastVerifiedAt: '2026-07-18',
    completeness: 'partial',
    status: 'active',
  },
  {
    id: 'hbtf-auto-loan',
    institutionId: 'housing-bank',
    nameEn: 'Auto Loan',
    nameAr: null,
    category: 'vehicle',
    structure: 'conventional-loan',
    amountRange: { minimum: Money.of('3000'), maximum: Money.of('150000') },
    termMonths: { minimum: 12, maximum: 96 },
    pricing: {
      kind: 'not-published',
      minimumAnnualRate: null,
      maximumAnnualRate: null,
      benchmarkName: null,
      margin: 'Rate depends on income, income source, financing ratio, and customer classification.',
      effectiveRatePublished: null,
    },
    salaryTransfer: 'not-published',
    earlySettlementText: null,
    sourceIds: ['hbtf-auto-loan'],
    lastVerifiedAt: '2026-07-18',
    completeness: 'partial',
    status: 'active',
  },
  {
    id: 'boj-auto-loan-5050',
    institutionId: 'bank-of-jordan',
    nameEn: '50/50 Auto Loan',
    nameAr: null,
    category: 'vehicle',
    structure: 'conventional-loan',
    amountRange: { minimum: null, maximum: Money.of('100000') },
    termMonths: { minimum: null, maximum: 60 },
    pricing: {
      kind: 'not-published',
      minimumAnnualRate: null,
      maximumAnnualRate: null,
      benchmarkName: null,
      margin: null,
      effectiveRatePublished: null,
    },
    salaryTransfer: 'not-required',
    earlySettlementText: null,
    sourceIds: ['boj-auto-loan'],
    lastVerifiedAt: '2026-07-18',
    completeness: 'partial',
    status: 'active',
  },
  {
    id: 'safwa-car-murabaha',
    institutionId: 'safwa-islamic',
    nameEn: 'Cars Financing (Murabaha)',
    nameAr: null,
    category: 'vehicle',
    structure: 'murabaha',
    amountRange: { minimum: Money.of('2000'), maximum: Money.of('100000') },
    termMonths: { minimum: null, maximum: 84 },
    pricing: {
      kind: 'not-published',
      minimumAnnualRate: null,
      maximumAnnualRate: null,
      benchmarkName: null,
      margin: 'Page states the profit rate is fixed for the financing period, but the percentage itself is not disclosed.',
      effectiveRatePublished: null,
    },
    salaryTransfer: 'not-required',
    earlySettlementText: null,
    sourceIds: ['safwa-car-financing'],
    lastVerifiedAt: '2026-07-18',
    completeness: 'minimal',
    status: 'active',
  },
  {
    id: 'ahli-finance-and-go',
    institutionId: 'jordan-ahli',
    nameEn: 'Finance & Go — Auto Loan',
    nameAr: null,
    category: 'vehicle',
    structure: 'conventional-loan',
    amountRange: { minimum: null, maximum: Money.of('100000') },
    termMonths: { minimum: 12, maximum: 96 },
    pricing: {
      kind: 'fixed-interest',
      minimumAnnualRate: Rate.fromPercent('3.625'),
      maximumAnnualRate: null,
      benchmarkName: null,
      margin: 'Flat rate "starting from" — actual rate may be higher depending on applicant.',
      effectiveRatePublished: null,
    },
    salaryTransfer: 'optional',
    earlySettlementText: null,
    sourceIds: ['ahli-finance-and-go'],
    lastVerifiedAt: '2026-07-18',
    completeness: 'partial',
    status: 'active',
  },
]
